[package]
name = "cloud_api_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12.7", features = ["blocking", "json", "stream"] }
